import { 
    UserCircle, 
    MessageSquare as MessageSquareText, 
    FileText, 
    Users2, 
    BarChartBig, 
    CalendarClock, 
    History as HistoryIcon, 
    Smile, 
    Settings, 
    ShieldAlert, 
    Lightbulb, 
    ClipboardList, 
    ShieldCheck, 
    ScrollText 
} from 'lucide-react';

export const newParentDashboardCardConfig = (t, studentData, primaryChildId, dashboardSummary) => [
  {
    id: 'childProfile',
    titleKey: 'parentDashboard.childProfile.title',
    descriptionKey: 'parentDashboard.childProfile.description',
    icon: UserCircle,
    color: 'text-indigo-400',
    bgColor: 'bg-slate-800/60', 
    hoverBgColor: 'hover:bg-slate-700/80',
    link: primaryChildId ? `/dashboard/student/${primaryChildId}/profile` : null,
    requiresChild: true,
    customContent: false,
  },
  {
    id: 'childInteractions',
    titleKey: 'parentDashboard.childInteractions.title',
    descriptionKey: 'parentDashboard.childInteractions.description',
    icon: MessageSquareText,
    color: 'text-sky-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: '/dashboard/child-interactions',
    requiresChild: true,
    customContent: false,
    count: dashboardSummary?.recent_interactions_count,
  },
  {
    id: 'accessReports',
    titleKey: 'parentDashboard.accessReports.title',
    descriptionKey: 'parentDashboard.accessReports.description',
    icon: FileText,
    color: 'text-emerald-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: '/dashboard/access-reports',
    requiresChild: true,
    customContent: false,
    count: dashboardSummary?.available_reports_count,
  },
  {
    id: 'directCommunication',
    titleKey: 'parentDashboard.directCommunication.title',
    descriptionKey: 'parentDashboard.directCommunication.description',
    icon: Users2,
    color: 'text-purple-400',
    bgColor: 'bg-purple-600/30', 
    hoverBgColor: 'hover:bg-purple-600/40',
    link: '/dashboard/direct-communication',
    requiresChild: false, 
    customContent: false,
  },
  {
    id: 'wellbeingAlerts',
    titleKey: 'parentDashboard.wellbeingAlerts.title',
    descriptionKey: 'parentDashboard.wellbeingAlerts.description',
    icon: ShieldAlert,
    color: 'text-orange-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: primaryChildId ? `/dashboard/student/${primaryChildId}/profile` : null, 
    requiresChild: true,
    customContent: true, 
  },
  {
    id: 'homeSupport',
    titleKey: 'parentDashboard.homeSupport.title',
    descriptionKey: 'parentDashboard.homeSupport.description',
    icon: Lightbulb,
    color: 'text-lime-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: null, 
    requiresChild: true,
    customContent: true,
  },
  {
    id: 'studentGeneralProgress',
    titleKey: 'parentDashboard.studentGeneralProgress.title',
    descriptionKey: 'parentDashboard.studentGeneralProgress.description',
    icon: ClipboardList,
    color: 'text-teal-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: '/dashboard/student-progress',
    requiresChild: true,
    customContent: true,
  },
  {
    id: 'currentSupportPlanInfo',
    titleKey: 'parentDashboard.currentSupportPlanInfo.title',
    descriptionKey: 'parentDashboard.currentSupportPlanInfo.description',
    icon: ShieldCheck,
    color: 'text-cyan-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: primaryChildId ? `/dashboard/student/${primaryChildId}/profile` : null, 
    requiresChild: true,
    customContent: true,
  },
  {
    id: 'schoolNotes',
    titleKey: 'parentDashboard.schoolNotes.title',
    descriptionKey: 'parentDashboard.schoolNotes.description',
    icon: ScrollText,
    color: 'text-fuchsia-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: null, 
    requiresChild: true,
    customContent: true,
  },
  {
    id: 'scheduleAppointment',
    titleKey: 'parentDashboard.scheduleAppointment.title',
    descriptionKey: 'parentDashboard.scheduleAppointment.description',
    icon: CalendarClock,
    color: 'text-yellow-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: '/dashboard/schedule-appointment',
    requiresChild: false,
    customContent: false,
    count: dashboardSummary?.upcoming_appointments_count,
  },
  {
    id: 'parentSettings',
    titleKey: 'parentDashboard.accountSettings.title',
    descriptionKey: 'parentDashboard.accountSettings.description',
    icon: Settings,
    color: 'text-slate-400',
    bgColor: 'bg-slate-800/60',
    hoverBgColor: 'hover:bg-slate-700/80',
    link: '/dashboard/parent-settings',
    requiresChild: false,
    customContent: false,
  },
];