import { BarChartBig, CalendarClock, MessageSquare as MessageSquareText, FileText, Settings, Smile, History as HistoryIcon, Users2 } from 'lucide-react';

export const parentDashboardCardConfig = [
  {
    id: 'childInteractions',
    titleKey: 'parentDashboard.childInteractions.title',
    descriptionKey: 'parentDashboard.childInteractions.description',
    icon: MessageSquareText,
    color: 'text-sky-400',
    bgColor: 'bg-sky-500/20',
    hoverBgColor: 'hover:bg-sky-500/30',
    link: '/dashboard/child-interactions',
    requiresChild: true,
  },
  {
    id: 'accessReports',
    titleKey: 'parentDashboard.accessReports.title',
    descriptionKey: 'parentDashboard.accessReports.description',
    icon: FileText,
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/20',
    hoverBgColor: 'hover:bg-emerald-500/30',
    link: '/dashboard/access-reports',
    requiresChild: true,
  },
  {
    id: 'directCommunication',
    titleKey: 'parentDashboard.directCommunication.title',
    descriptionKey: 'parentDashboard.directCommunication.description',
    icon: Users2,
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/20',
    hoverBgColor: 'hover:bg-purple-500/30',
    link: '/dashboard/direct-communication',
    requiresChild: false, 
  },
  {
    id: 'studentProgress',
    titleKey: 'parentDashboard.studentProgress.title',
    descriptionKey: 'parentDashboard.studentProgress.description',
    icon: BarChartBig,
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/20',
    hoverBgColor: 'hover:bg-rose-500/30',
    link: '/dashboard/student-progress',
    requiresChild: true,
  },
  {
    id: 'scheduleAppointment',
    titleKey: 'parentDashboard.scheduleAppointment.title',
    descriptionKey: 'parentDashboard.scheduleAppointment.description',
    icon: CalendarClock,
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/20',
    hoverBgColor: 'hover:bg-yellow-500/30',
    link: '/dashboard/schedule-appointment',
    requiresChild: false,
  },
  {
    id: 'appointmentHistory',
    titleKey: 'parentDashboard.appointmentHistory.title',
    descriptionKey: 'parentDashboard.appointmentHistory.description',
    icon: HistoryIcon,
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/20',
    hoverBgColor: 'hover:bg-blue-500/30',
    link: '/dashboard/appointment-history',
    requiresChild: false,
  },
   {
    id: 'parentUnified',
    titleKey: 'parentDashboard.unifiedProgress.pageTitle',
    descriptionKey: 'parentDashboard.unifiedProgress.pageSubtitle',
    icon: Smile,
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/20',
    hoverBgColor: 'hover:bg-pink-500/30',
    link: '/dashboard/progress-quick-access', 
    requiresChild: true,
  },
  {
    id: 'parentSettings',
    titleKey: 'parentDashboard.accountSettings.title',
    descriptionKey: 'parentDashboard.accountSettings.description',
    icon: Settings,
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/20',
    hoverBgColor: 'hover:bg-slate-500/30',
    link: '/dashboard/parent-settings',
    requiresChild: false,
  },
];